/**
 * Stable, machine-readable error codes. Clients (web and mobile) branch on
 * these rather than on human-readable messages, so the strings must not change
 * once released.
 */
export enum ErrorCode {
  // Generic
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED = 'OTP_ATTEMPTS_EXCEEDED',
  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  PASSWORD_REUSED = 'PASSWORD_REUSED',

  // Authorization / tenancy
  MISSING_PERMISSION = 'MISSING_PERMISSION',
  TENANT_MISMATCH = 'TENANT_MISMATCH',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  MODULE_DISABLED = 'MODULE_DISABLED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_LIMIT_REACHED = 'SUBSCRIPTION_LIMIT_REACHED',
  SCHOOL_SUSPENDED = 'SCHOOL_SUSPENDED',

  // Domain
  DUPLICATE_ADMISSION_NUMBER = 'DUPLICATE_ADMISSION_NUMBER',
  DUPLICATE_EMPLOYEE_ID = 'DUPLICATE_EMPLOYEE_ID',
  SECTION_CAPACITY_EXCEEDED = 'SECTION_CAPACITY_EXCEEDED',
  ATTENDANCE_ALREADY_MARKED = 'ATTENDANCE_ALREADY_MARKED',
  ATTENDANCE_LOCKED = 'ATTENDANCE_LOCKED',
  ATTENDANCE_FUTURE_DATE = 'ATTENDANCE_FUTURE_DATE',
  HOLIDAY_NO_ATTENDANCE = 'HOLIDAY_NO_ATTENDANCE',
  TIMETABLE_TEACHER_CONFLICT = 'TIMETABLE_TEACHER_CONFLICT',
  TIMETABLE_ROOM_CONFLICT = 'TIMETABLE_ROOM_CONFLICT',
  TIMETABLE_SECTION_CONFLICT = 'TIMETABLE_SECTION_CONFLICT',
  MARKS_LOCKED = 'MARKS_LOCKED',
  MARKS_EXCEED_MAXIMUM = 'MARKS_EXCEED_MAXIMUM',
  EXAM_NOT_PUBLISHABLE = 'EXAM_NOT_PUBLISHABLE',
  RESULTS_NOT_PUBLISHED = 'RESULTS_NOT_PUBLISHED',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',
  INVOICE_CANCELLED = 'INVOICE_CANCELLED',
  PAYMENT_AMOUNT_EXCEEDS_BALANCE = 'PAYMENT_AMOUNT_EXCEEDS_BALANCE',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  REFUND_EXCEEDS_PAYMENT = 'REFUND_EXCEEDS_PAYMENT',
  GATEWAY_ERROR = 'GATEWAY_ERROR',
  BOOK_NOT_AVAILABLE = 'BOOK_NOT_AVAILABLE',
  BOOK_LIMIT_REACHED = 'BOOK_LIMIT_REACHED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  VEHICLE_CAPACITY_EXCEEDED = 'VEHICLE_CAPACITY_EXCEEDED',
  LEAVE_BALANCE_EXCEEDED = 'LEAVE_BALANCE_EXCEEDED',
  LEAVE_OVERLAP = 'LEAVE_OVERLAP',
  ACADEMIC_YEAR_LOCKED = 'ACADEMIC_YEAR_LOCKED',

  // Files
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  STORAGE_QUOTA_EXCEEDED = 'STORAGE_QUOTA_EXCEEDED',
}
