/**
 * Prisma models that carry a `schoolId` column and therefore belong to exactly
 * one tenant. Any query against these models must be filtered by schoolId.
 *
 * The list is asserted against the generated Prisma DMMF at boot
 * (see TenantGuardExtension), so adding a tenant-scoped model to the schema
 * without registering it here fails fast rather than silently leaking data.
 */
export const TENANT_SCOPED_MODELS = new Set<string>([
  'Subscription',
  'Role',
  'User',
  'AcademicYear',
  'Department',
  'Designation',
  'Class',
  'Section',
  'Subject',
  'Room',
  'Holiday',
  'Student',
  'Guardian',
  'Enrollment',
  'Staff',
  'SalaryStructure',
  'Attendance',
  'StaffAttendance',
  'Period',
  'TimetableSlot',
  'Homework',
  'Assignment',
  'GradeScale',
  'Exam',
  'ReportCard',
  'FeeHead',
  'FeeStructure',
  'Discount',
  'Invoice',
  'Payment',
  'Refund',
  'LedgerEntry',
  'NumberSequence',
  'Notice',
  'Notification',
  'Conversation',
  'LeaveType',
  'LeaveRequest',
  'Event',
  'Complaint',
  'Vehicle',
  'Driver',
  'TransportRoute',
  'BookCategory',
  'Book',
  'LibraryMembership',
  'LibraryIssue',
  'InventoryCategory',
  'Supplier',
  'InventoryItem',
  'Purchase',
  'StockTransaction',
  'DocumentCategory',
  'Document',
  'AuditLog',
  'JobRun',
  'AdmissionEnquiry',
  'CertificateTemplate',
  'Certificate',
  'IdCard',
  'SupportTicket',
  'WebsitePage',
  'GalleryAlbum',
  'Attachment',
]);

/**
 * Models whose `schoolId` is nullable because platform-level rows exist
 * (super admin users, global roles, platform audit entries). A null schoolId on
 * these models means "belongs to the platform, not to any school".
 */
export const NULLABLE_TENANT_MODELS = new Set<string>([
  'User',
  'Role',
  'AuditLog',
  'JobRun',
  'Notification',
  'SupportTicket',
  'DocumentCategory',
  'CertificateTemplate',
  'Attachment',
]);

/** Models reachable only through a tenant-scoped parent, so not filtered directly. */
export const CHILD_MODELS = new Set<string>([
  'RolePermission',
  'UserRole',
  'UserPermission',
  'Session',
  'Device',
  'OtpCode',
  'VerificationToken',
  'Permission',
  'SubscriptionPlan',
  'ClassSubject',
  'SubjectTeacher',
  'StudentGuardian',
  'TimetableSubstitution',
  'HomeworkSubmission',
  'AssignmentSubmission',
  'GradeBand',
  'ExamClass',
  'ExamSubject',
  'ExamSchedule',
  'Mark',
  'MarkRevision',
  'ReportCardExam',
  'FeeStructureItem',
  'FeeInstallment',
  'StudentDiscount',
  'InvoiceItem',
  'PaymentAllocation',
  'NoticeRead',
  'NotificationDelivery',
  'NotificationPreference',
  'ConversationMember',
  'Message',
  'MessageReceipt',
  'LeaveBalance',
  'EventRegistration',
  'RouteStop',
  'StudentTransport',
  'VehiclePosition',
  'BookCopy',
  'LibraryFine',
  'PurchaseItem',
  'TicketMessage',
  'GalleryPhoto',
]);
